# Generated by Django 5.1.4 on 2024-12-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Rent', 'Rent'), ('Food', 'Food'), ('Entertainment', 'Entertainment'), ('Salary', 'Salary'), ('Utilities', 'Utilities')], max_length=20),
        ),
    ]
