# Generated by Django 5.1.4 on 2024-12-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Food', 'Food'), ('Entertainment', 'Entertainment'), ('Salary', 'Salary'), ('Utilities', 'Utilities')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=20),
        ),
    ]
